### ISSUE TITLE
I want to add C programs

### ISSUE THREAD

**Issue by rnavaneeth992** [TheAlgorithms/C#1011]
### What would you like to share?

The things I want to add
1) Infix to Postfix

**Comment by rnavaneeth992** [comment]
Can you please assign

**Comment by Prathamrajbhatt** [comment]
Hey! Can you please assign me this issue?

**Comment by SohamPashteSSP** [comment]
Hello, can you assign me with this? I can add C program for converting Infix to Postfix and also for Evaluating Postfix expression

**Comment by srusti610** [comment]
sir,
can you assign this to me.

**Comment by AyushCSE04** [comment]
Can You Assign this to me , this is my first contribution.

**Comment by Go3452** [comment]
sir , plz assign me this issue.

**Comment by gopal8220** [comment]
Please Assign it to me I want to add some good C programs to this issue.

**Comment by Meghwantsingh** [comment]
Can you please assign me

**Comment by ZohaiAli** [comment]
Hello sir!
please assign me this task. I am adding my C project to your account.

**Comment by SwaggyRajput** [comment]
Hello sir, Can u assign me this issue. I would love to grab this opportunity

**Comment by SourishJoshi8** [comment]
Hi, plz assign this to me

**Comment by 12manisha** [comment]
can you assign it to me? i would like to work in it
