### ISSUE TITLE
I want to add Leetcode programs

### ISSUE THREAD

**Issue by rnavaneeth992** [TheAlgorithms/C#1012]
### What would you like to share?

2427. Number of Common Factors
2428. Maximum Sum of an Hourglass

**Comment by rnavaneeth992** [comment]
Can you please assign me

**Comment by hussainiftikhar5242** [comment]
Can You please Assign it to me @rnavaneeth992 .

**Comment by srusti610** [comment]
Sir,
can you please assign this to me.

**Comment by psrp7** [comment]
sir please assign me this i want to add c++ and java solution for this problem a brute force appraoch as well as best optimized approach

**Comment by Meghwantsingh** [comment]
New to leetcode but kindly assign this to me.

**Comment by akashissu** [comment]
Assign Me this Problem.

**Comment by anuragsahay5** [comment]
Hello, Can you assign me Q2427.

**Comment by SourishJoshi8** [comment]
hi,
i would like to try this,
plz assign to me
