### ISSUE TITLE
Circular Queue

### ISSUE THREAD

**Issue by SohamPashteSSP** [TheAlgorithms/C#1024]
### Detailed description

In queue folder, I didn't saw a program for Circular Queue, hence I thought adding this will be of good use to reader since circular queue is an important modification of queue.

### Context

Users/Reader will get to know how circular queue is implemented.

**Comment by SohamPashteSSP** [comment]
Hello, please assign me with task

**Comment by aromalsanthosh** [comment]
@SohamPashteSSP Can u assign me this ?

**Comment by impragya08** [comment]
Hi,

I have not seen any implementation of Circular Queue in this repo.
Could you please assign this issue to me?

Regards,
Pragya

**Comment by hussainiftikhar5242** [comment]
Hi @SohamPashteSSP  Can you assign this task to me, i want to contribute on it.

**Comment by aniket-varma** [comment]
Please assign this issue to me

**Comment by ZohaiAli** [comment]
Hi sir! 
I already done this task please assign me this task then I can send the code
