### ISSUE TITLE
[FEATURE] Beginners friendly Array implementation

### ISSUE THREAD

**Issue by Saradwata-Bandyopadhyay** [TheAlgorithms/C#1029]
### Detailed description

The code provided in the Array Repository can only be understood by advanced C users. I hereby propose a basic array implementation and performing some basic operations using the same array implementation.

### Context

This repository according to its description states that it consists of various Algorithms implementation using C language. But the code mentioned in the repository cannot be used by novice coders or other interested people easily. So I suggest a commonly used method of representing arrays along with its commonly used operations.

**Comment by Saradwata-Bandyopadhyay** [comment]
Please assign this issue to me.

**Comment by astitva0011** [comment]
!assign

**Comment by Go3452** [comment]
assign me this issue?

**Comment by Vivek-04022001** [comment]
Hey, I'm interested in this issue. Can i contribute in it?

**Comment by abhople1902** [comment]
Hey, I'm interested in this issue and would like to contribute. Please assign me.

**Comment by akashissu** [comment]
Please assign Me This Issue.

**Comment by aniket-varma** [comment]
Please Assign me this issue

**Comment by ayushsinghh039** [comment]
Can you please assign this task to me?
Will be a great opportunity for me... I can add a lot many usable ARRAY functions for known and necessary algorithms.
Will be great!!!

**Comment by SourishJoshi8** [comment]
hey,
i would like to work on this,
plz assign it to me
