### ISSUE TITLE
[FEATURE] Implement Linked list and its operations

### ISSUE THREAD

**Issue by Saradwata-Bandyopadhyay** [TheAlgorithms/C#1030]
### Detailed description

A comprehensive code consisting of all the Linked List along with its operations is missing in this repository.

### Context

Linked List is a commonly used Data Structure. So a code consisting of all its implementations using functions would help in getting an better overview of this data structure and will also act as a reference for future use.

**Comment by Saradwata-Bandyopadhyay** [comment]
Please assign this issue to me.

**Comment by tusharnain4578** [comment]
Please assign this to me, I will write fully documented code.

**Comment by MoitreyoChak** [comment]
Hey , I am interested in this task and would like to contribute to this issue.

**Comment by MoitreyoChak** [comment]
shall i create the Linked_List.c  file inside the data structure folder?

**Comment by Go3452** [comment]
can you assign me this issue?

**Comment by Emmastro** [comment]
There are some functions on linked list on the data structure directory, though there are just very few implementations. I just opened a PR for inserting a node on a singly linked list on a particular index from https://github.com/TheAlgorithms/C/pull/1039

**Comment by Vivek-04022001** [comment]
Hey, I'm interested in this issue. Can i contribute in it?

**Comment by drashan14** [comment]
Hello sir,
I would like to do this task could you assign me this task.

**Comment by konan625** [comment]
Hello sir, Can you assign this task to me?

**Comment by aniket-varma** [comment]
Please assign me this task

**Comment by AnanyaBajpayi** [comment]
Please assign this issue to me.

**Comment by SwaggyRajput** [comment]
Hello sir, can u assign me this issue. I would love to grab this opportunity.

**Comment by thebarshablog** [comment]
Is this issue still open for contribution? I've the materials ready that needs to be uploaded. Please assign.

**Comment by Panquesito7** [comment]
> Is this issue still open for contribution? I've the materials ready that needs to be uploaded. Please assign.

Thank you for your interest in contributing! 🎉
Before submitting a PR, please ensure the following:

- The algorithm/implementation isn't a duplicate in this repository.
- Make your code per the repository [standards](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md).
- Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C/actions) pass.

I'll look forward to reviewing your PR. Thanks. 🙂
