### ISSUE TITLE
[OTHER] Update all Discord links

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/C#1054]
### What would you like to share?

We're using a new link for The Algorithms' Discord invitation.
All Discord invitation links should point to `https://the-algorithms.com/discord/`.

### Additional information

This is a good first issue. Please leave it open to first-time contributors and beginners. 🙂

**Comment by ritikal167** [comment]
Does this project fall under hactoberfest-2022 ?

**Comment by Panquesito7** [comment]
> Does this project fall under hactoberfest-2022 ?

Hello! The project itself does, however, this issue doesn't count for Hacktoberfest.
