### ISSUE TITLE
Adding Leetcode Problem

### ISSUE THREAD

**Issue by anuragsahay5** [TheAlgorithms/C#1075]
### Detailed description

I want to Add the LeetCode Problem No. 968 Binary Tree Cameras Hard.

### Context

It will help to understand how we can solve hard problems containing tree data structures.

### Possible implementation

Dynamic Programming
Depth First Search

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing! 🎉
Before submitting a PR, please ensure the following:

- The algorithm/implementation isn't a duplicate in this repository.
- Make your code per the repository [standards](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md).
- Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C/actions) pass.

**Comment by SwaggyRajput** [comment]
Hello sir, can u assign me this issue. I would love to grab this opportunity.

**Comment by Panquesito7** [comment]
@anuragsahay5, do you still want to work on this?
