### ISSUE TITLE
I want to add leetcode problem #75

### ISSUE THREAD

**Issue by satvik202** [TheAlgorithms/C#1112]
### Adding leetcode problem 75

problem link : https://leetcode.com/problems/sort-colors/

problem type: medium

using concept: Arrays, Sorting.

**Comment by SnehalSa** [comment]
Hello Sir,
Can You assign this issue to me?

**Comment by v1shant** [comment]
Hii Satvik,
Could you assign me this issue?

**Comment by 11nitis** [comment]
hey!
can you assign this task to me this is my first time at hactoberfest if you assign this this will be baby step for me to contribute in open source community.
thank  you..
