### ISSUE TITLE
Add NumberBaseball Game

### ISSUE THREAD

**Issue by kanghyejong1001** [TheAlgorithms/C#1149]
### Detailed description

I want to add C program file of NumberBaseball Game in Games. 

This game is a game that matches randomly generated three digits against a computer.

### Context

New Game

It is a game that can be made using only basic grammar such as conditional sentences and repetitive sentences, and I think I can develop my skills by writing code at my current level.

### Additional information

Now I'm practicing open source contributions in course, "the open software practice", at our school. 

Subject ratings are determined through issue registration and PR merge. 

I would like to develop an open-source contribution experience by programming this number baseball game code and registering issues. 

Thank you.

**Comment by Panquesito7** [comment]
Hello, thank you for your interest! Sounds very interesting to me. @tjgurwara99, @appgurueu, what do you think about this?

**Comment by appgurueu** [comment]
Sounds like a trivial "guess the number" variant, not sure whether it'd add much value to the algo repo.

**Comment by tjgurwara99** [comment]
It is an interesting idea 😄 however I agree with @appgurueu on this that this would be a trivial guessing game without adding the kind of value that we want contributions to provide in this repository 😓

Maybe consider adding some other algorithm, we're always happy to discuss new ideas 😄

**Comment by kanghyejong1001** [comment]
I see. Thank you for reply.

**Comment by Panquesito7** [comment]
Will be closing for now. Thanks.
