### ISSUE TITLE
[FEATURE] Update LeetCode contributing guide

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/C#1224]
### Detailed description

The LeetCode contributing guide states to add your LeetCode problem to the `DIRECTORY.md` file.
However, this is no longer needed as it is done by a [GitHub workflow](https://github.com/TheAlgorithms/C/blob/master/.github/workflows/leetcode_directory_writer.yml).

### Context

We should update the guide ASAP as it could confuse users and waste their time in that.

**Comment by alexpantyukhin** [comment]
I think it was fixed by this https://github.com/TheAlgorithms/C/pull/1225
