### ISSUE TITLE
[FEATURE] New directory for ciphers?

### ISSUE THREAD

**Issue by dsmurrow** [TheAlgorithms/C#1235]
### Detailed description

Add a new directory to put encryption/decryption algorithms (the only cipher I've seen implemented here currently is ROT13).

### Context

I have at least 2 or 3 ciphers I would like to implement (Affine, Hill, AES) and putting them with ROT13 in the misc directory just seems like unnecessary inflation. This would also help users know where to look for cipher algorithms.

### Possible implementation

If enough people are interested I can do a PR to make the directory and move rot13 into there. I'll also add some of my own cipher implementations there soon enough. I didn't feel comfortable doing it without asking first.

**Comment by Panquesito7** [comment]
This sounds great! Feel free to create a PR and also a new directory for ciphers. 🙂
If you need any help, let us know here or on our [Discord community](https://the-algorithms.com/discord).
