### ISSUE TITLE
[OTHER] Shouldn't we update the copyright notice's time to 2023?

### ISSUE THREAD

**Issue by CascadingCascade** [TheAlgorithms/C#1242]
### What would you like to share?

I just noticed that the time in the [license](https://github.com/TheAlgorithms/C/blob/master/LICENSE) is still 2016-2022, shouldn't we change it to 2023?

**Comment by alexpantyukhin** [comment]
I'm not sure is it required or not. Maybe we can make a job which runs one time per day and check if the year is changed - make a   PR ?

**Comment by Panquesito7** [comment]
Would be better to check each year on the 1st day of January, maybe. 🤔

**Comment by alexpantyukhin** [comment]
oh, if its possible to schedule - yes, I think :)

**Comment by Panquesito7** [comment]
https://github.com/TheAlgorithms/scripts/issues/21
