### ISSUE TITLE
[FEATURE] Update CMake to a newer version

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/C#1271]
### Detailed description

It appears the version we're currently using is 3.6.0, which was released around [2016](https://cmake.org/pipermail/cmake/2016-November/064471.html).
I think it'd be great if we could update to a newer version, **such as 3.9, like the C++ repository**, to have more security fixes, and features, as well as be up-to-date and ensure our project works with the latest versions.

### Context

This will ensure we have the latest security fixes and features, and make sure our project works with the latest versions of CMake.

### Possible implementation

Upgrade CMake to a newer or the latest version (the current version is 3.6.0).

**Comment by rbevin777** [comment]
If you think this would still be useful I can work on it.

**Comment by Panquesito7** [comment]
> If you think this would still be useful I can work on it.

It'd be great, thanks! 🙂
