### ISSUE TITLE
[FEATURE] Add Windows builds back

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/C#1274]
### Detailed description

Many people still develop and test algorithms on Windows, not only in Linux or MacOS.
However, this repository only has Linux and MacOS support, which if not well-tested on Windows, the code may have errors.

I suggest adding back the Windows builds. There are a few errors, but those can be fixed.

### Context

1. Windows users do not have to worry about errors or unwanted things happening when building.
2. This ensures the code works perfectly fine on the latest Windows versions.
3. MSVC (sometimes) catches a few other errors the other compilers do not.

### Possible implementation

Add Windows builds back.

### Additional information

I'd like to work on this, if agreed to add them back.

**Comment by Panquesito7** [comment]
Looks like Scilab has the `fork` function implemented in Windows. https://github.com/scilab/scilab/tree/master/scilab/modules/parallel/src/c
What do you folks think? Should we give it a try?

**Comment by realstealthninja** [comment]
> Looks like Scilab has the `fork` function implemented in Windows. https://github.com/scilab/scilab/tree/master/scilab/modules/parallel/src/c
> What do you folks think? Should we give it a try?
> 

I think it's worth the shot if it works then we're good to go!

**Comment by ldo** [comment]
You could just support building the code under Cygwin. That would give you a more Unix/Linux-like environment than native Windows can manage on its own.
