### ISSUE TITLE
[OTHER] Inconsistent coding style with `.clang-format`

### ISSUE THREAD

**Issue by danielhu19** [TheAlgorithms/C#1275]
### What would you like to share?

What is the **actual** coding style for Algorithms/C? 

The online documentation suggests that this should be consistent with the [CMU Style](https://users.ece.cmu.edu/~eno/coding/CCodingStandard.html), which has been followed with `CONTRIBUTION GUIDELINES`. 
However, it appears that the use of parentheses in all code within the repository does not conform to this CMU coding style.

### Additional information

I wasted 30 min on this: I thought that there was an issue with my VS Code settings or with Clang-Format, but I later realized that the problem was with the inconsistency between the .clang-format file and the coding standards.

**Comment by danielhu19** [comment]
> Those coding guidelines are very old now (5+ years).
> We probably should either remove it or update them.

I think the coding style of CMU is very good, and LLVM and Google both use this type of formatting for their parentheses. Therefore, I think it's better to **reformat** the code in the repository.

**Comment by Panquesito7** [comment]
Sounds good to me.
We should wait for the input of other maintainers, though.

**Comment by realstealthninja** [comment]
> > Those coding guidelines are very old now (5+ years).
> > We probably should either remove it or update them.
> 
> I think the coding style of CMU is very good, and LLVM and Google both use this type of formatting for their parentheses. Therefore, I think it's better to **reformat** the code in the repository.

CMU sounds good

**Comment by danielhu19** [comment]
I've modified the `.clang-format' **within** my PR #1283, which satisfies the CMU coding standard.
