### ISSUE TITLE
[FEATURE] improve the naming of variables

### ISSUE THREAD

**Issue by haru02w** [TheAlgorithms/C#1291]
### Detailed description

The variable names used in `sorting/merge_sort.c` is really confusing. Please, use more useful names:
`int *aux_array` instead of `int *b`

### Context

Sorry, I cannot understand what the code is doing

**Comment by BamaCharanChhandogi** [comment]
Hey, I can contribute. Can you assign me?

**Comment by alexpantyukhin** [comment]
@BamaCharanChhandogi You are free to make a PR and link the issue on the PR. No need to assign for that.

**Comment by BamaCharanChhandogi** [comment]
Hey, @alexpantyukhin  check #1294 PR

**Comment by PratushRai** [comment]
Is this issue still open??
