### ISSUE TITLE
Fet: add Postfix To Infix 

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [TheAlgorithms/C#1299]
### Detailed description

I think Postfix To Infix is missing. so I want to add this algo. 

### Context

This algorithm is very important for C language.

**Comment by Sampadaa1729** [comment]
Hi, Can I make PR for this ?

**Comment by BamaCharanChhandogi** [comment]
yes, you can make it.

**Comment by NiranjanLangade** [comment]
Can you assign this issue to me please !!

**Comment by Kavyashah26** [comment]
@BamaCharanChhandogi I have started working on this algo 
Looking forward to contribute

**Comment by atharv-kanbargi** [comment]
I have worked on this issue before. Please assign me to this issue so that I can create a PR for it.

**Comment by shreyasrajiv327** [comment]
I would like to contribute for this issue,Can i make a PR for this?

**Comment by akshithagunupati** [comment]
Hi @BamaCharanChhandogi can I work on this issue please?
