### ISSUE TITLE
Fet: add "Prefix Evaluation" algo

### ISSUE THREAD

**Issue by BamaCharanChhandogi** [TheAlgorithms/C#1300]
### Context

This algorithm is very important.

**Comment by Priyanka-Das-0** [comment]
Hey can I make a PR for this?

**Comment by Saket03-P** [comment]
Hello @BamaCharanChhandogi, 

I'm willing to work on the prefix evaluation issue of this repo. After carefully considering the contribution guidelines, issue description, and language requirements, and my experience with `C/C++` for DSA and Competitive Programming; I'm excited to work on it. 

Please consider assigning this issue to me. I look forward to contributing to this project and helping resolve this problem. Although I'm a bit late, I want to assue you of my task effectiveness in completing this issue.

**Comment by Jayan-Shah** [comment]
Hello @BamaCharanChhandogi 
I am willing to work on this current problem so please assign me this problem

**Comment by CascadingCascade** [comment]
There's no need to ask to be assigned or ask whether you can open a PR, if you can contribute, just write your code then open a PR. The contribution guidelines also mentioned this:
```
Issues Please avoid opening issues asking to be "assigned” to a particular algorithm. This merely creates unnecessary noise for maintainers. Instead, please submit your implementation in a pull request, and it will be evaluated by project maintainers.
```
