### ISSUE TITLE
[FEATURE] [NEW ALGO] Infix to Prefix

### ISSUE THREAD

**Issue by Kavyashah26** [TheAlgorithms/C#1314]
### Detailed description

Detailed description
I think Infix To prefix  algo is missing, so I want to add this algo and contribute.

Context
This algorithm is very important for understanding conversions of expressions.

Possible implementation
No response

Additional information
No response

### Context

I am willing to contribute this algo .
This will help others to understand the logic behind conversion of expressions

**Comment by AvinashReddy19** [comment]
can you assign me this issue

**Comment by sahill-chand** [comment]
@Kavyashah26 Kavyashah26.Please assign me this project.I will complete this project in just one day by using comments and appropriate variable names and in most efficient way.Desperately Looking ahead to work with you.

**Comment by Kavyashah26** [comment]
@PRONOBITA I am also here to contribute , Just check I am the only one who has opened this issue.
I am also waiting for approval from maintainers .

**Comment by CascadingCascade** [comment]
There's no need to ask to be assigned, if you can contribute, just write your code then open a PR. The contribution guidelines also mentioned this:
```
Issues Please avoid opening issues asking to be "assigned” to a particular algorithm. This merely creates unnecessary noise for maintainers. Instead, please submit your implementation in a pull request, and it will be evaluated by project maintainers.
```
