### ISSUE TITLE
[FEATURE][NEW ALGO] factorial recursion

### ISSUE THREAD

**Issue by peeplika** [TheAlgorithms/C#1326]
### Detailed description

factorial recursion in c was missing

### Context

It was implemented in java and dart but not c

**Comment by Vector-013** [comment]
Thank you, I have implemented the feature

**Comment by himanchal08** [comment]
i would like to work on this issue it seems doable
i will try my best to implement it

**Comment by Arya-Hari** [comment]
Hi I would really love to work on this issue. I have a year's worth of experience in C and believe that I can resolve this. Thank you for your consideration.
