### ISSUE TITLE
[BUG] Broken/Wrong code in C/conversions /hexadecimal_to_octal.c

### ISSUE THREAD

**Issue by sk-jiyad** [TheAlgorithms/C#1330]
### Description

The code provides returns wrong value after conversion from Hexadecimal to octal.

### Expected behavior

Should return the correct converted value.

### Actual behavior

The code provides wrong output in conversion, and even returns negative integers after conversion.

### Steps to reproduce

Just run the code in your IDE.

### Context

N/A

### Additional information

Kindly assign me this issue. I am willing to help asap.

**Comment by sk-jiyad** [comment]
@Panquesito7  Pls check this once

**Comment by sk-jiyad** [comment]
@Panquesito7  @tjgurwara99 @alexpantyukhin Pls Check This issue

**Comment by himanchal08** [comment]
i would like to work on this issue it seems doable
i will try my best to implement it
