### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by shivamdroidoreo** [TheAlgorithms/C#1416]
### What would you like to share?

Potential Improvements:
Loop Start Index: In the loop, i starts from 0 and runs for n - 2 iterations. This works but can be slightly optimized by starting the loop from i = 3 and running until i <= n. This way, the loop becomes more intuitive as it directly matches the Tribonacci sequence progression.

Variable Naming: nextT could be renamed to something more descriptive, like nextTerm, to indicate that it is the next Tribonacci number.

**Comment by VyankateshRohokale** [comment]
can you provide more information for me to work on it
