### ISSUE TITLE
Want to Add more Sorting Algorithms in C

### ISSUE THREAD

**Issue by UdaySharmaGitHub** [TheAlgorithms/C#1420]
### Detailed description

Want to Add more Sorting Algorithms in C like.
- TimSort
- Bitonic Sort
- 3-way MergeSort
- Please Assign me this issue under Hacktoberfest or Hacktoberfest2024

### Context

These Sorting Algorithms not many people Know about it .

### Possible implementation

we can use Sub folder to divide the programs in topic wise manner

**Comment by Shreyaww** [comment]
Can you please assign this issue to me as this would be my first contribution in hacktoberfest

**Comment by SpEXterXD** [comment]
Waiting for approval. #1421

**Comment by UdaySharmaGitHub** [comment]
@Shreyaww you can contribute on it.
- i believe in First come and first serve

**Comment by VyankateshRohokale** [comment]
I would like to contribute, can you assign this issue to me too

**Comment by UdaySharmaGitHub** [comment]
@VyankateshRohokale you can add but make sure its must be unique mean 
you can contribute those algo which is not present in the repo

**Comment by Mrutyunjaypathe** [comment]
Me and @VyankateshRohokale will work on it together (we know each other ) you can assign this issue to both of us , will solve this issue

**Comment by VyankateshRohokale** [comment]
Yes, I am up , let's do it

**Comment by real68** [comment]
I'm in with Aria & ChatGPT but I'm banned overwhiles.

Il lun 7 ott 2024, 09:09 Vyankatesh Rohokale ***@***.***> ha
scritto:

**Comment by FaheemorFAB** [comment]
assign me the issue please.
