### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by zphiliam** [TheAlgorithms/C#223]
C/data_structures/stack.c

I think there is a bug !

the `node->next` always equal to `NULL`

**Comment by itaikla** [comment]
You are right, node->next is always equal to NULL, but it's not a bug, the author just did not use it.
Because you actually can implement a stack with only one pointer to next node (prev or node in that case is a semantic issue), like singly linked list.

**Comment by ashwek** [comment]
@zphiliam thank you for reporting the issue.
well ``node->next`` being ``NULL`` is not a bug, but due to this

https://github.com/TheAlgorithms/C/blob/b1fed3cf3e9f693a653750ec4e402a6ff75f9095/data_structures/stack.c#L111

this line becomes useless.
