### ISSUE TITLE
Algorithms C stack, Why not free the orgin memory

### ISSUE THREAD

**Issue by megahertz66** [TheAlgorithms/C#242]
In fuction `void grow()`  On line 53. The copy element has been completed. Why not free the orgin memory.

**Comment by danghai** [comment]
Could you give me the link of the file?

**Comment by megahertz66** [comment]
https://github.com/TheAlgorithms/C/blob/master/data_structures/stack/stack.c
Only `malloc` in this file and no `free`

**Comment by danghai** [comment]
Hi @megahertz66 . Could you open a PR to resolve it? Thank you

**Comment by megahertz66** [comment]
Hello @danghai. The PR is ok. Please review the code.

**Comment by megahertz66** [comment]
@danghai . The PR is ok.

**Comment by ashwek** [comment]
issue resolved in PR #243
