### ISSUE TITLE
Add more solution for Leetcode algorithm.

### ISSUE THREAD

**Issue by danghai** [TheAlgorithms/C#249]
I create leetcode directory. You can contribute solution for Leetcode algorithm by C language.
Good practice coding :)
Please put some comment for explanation. It helps other people understand your algorithm better

**Comment by SuranjanDaw** [comment]
Added 7.c: Integer reversal with 32-bit overflow checker  and 9.c: Pallidrome without string conversion

**Comment by shubhamdpatil** [comment]
Added Leetcode solutions for problem no: 2, 4, 7, 8, 21, 28
PR: #349

**Comment by Kunal614** [comment]
Unique Number of Occurrences 1207
https://github.com/TheAlgorithms/C/pull/422

**Comment by kvedala** [comment]
This is an excellent collection 👍 

Can you please convert the codes to independent executable programs with documentation in sync with the rest of the repo? Thanks

**Comment by BhanukaC** [comment]
#703

**Comment by BhanukaC** [comment]
Add LeetCode Problem 1486 using C #703

**Comment by BhanukaC** [comment]
> I create leetcode directory. You can contribute solution for Leetcode algorithm by C language.
> Good practice coding :)
> Please put some comment for explanation. It helps other people understand your algorithm better

Add LeetCode Problem 1486 using C #703

**Comment by BhanukaC** [comment]
Add LeetCode Problem 1486 using C #703

**Comment by BhanukaC** [comment]
LeetCode 961 Problem Using C #702

**Comment by BhanukaC** [comment]
Create 1295.c #701

**Comment by itsvinayak** [comment]
hey @danghai, how to add an alternate algorithm for the same question, should it be added to the same file or by creating another file, what should be the syntax for naming file?

thank you,
@itsvinayak

**Comment by kvedala** [comment]
> hey @danghai, how to add an alternate algorithm for the same question, should it be added to the same file or by creating another file, what should be the syntax for naming file?
> 
> thank you,
> @itsvinayak

[Contribution Guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md)
Meanwhile, the Leetcode folder is currently unstructured and there is an effort to normalize the folder with respect to the repo #733

**Comment by DhruvPasricha** [comment]
Hi @danghai, I would like to work on this issue,.
Can i contribute by adding some solutions ?

**Comment by Panquesito7** [comment]
> Can I contribute

Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

**Comment by Dezx20** [comment]
Hi @danghai  im new into this and i would love to contribute in this sections. can u help me with how i can get started, Please?

**Comment by AryanNayak** [comment]
Hey, can I contribute to this? I have solved 800+ questions on Leetcode.

**Comment by Panquesito7** [comment]
> Hey, can I contribute to this? I have solved 800+ questions on Leetcode.

Woah, amazing! Of course, you can! Feel free to make PRs, and we'll review them. 🙂

**Comment by Ayan-thecodeking** [comment]
I also want to add some leetcode questions ...as I have practiced a lot 
Pls assign it to me under hacktoberfest

**Comment by AyushSingh-github** [comment]
hello. i just added my 4 leetcode solutions for binary tree transversals. please see my pull request.
