### ISSUE TITLE
not working bubbleSort

### ISSUE THREAD

**Issue by MNCODE** [TheAlgorithms/C#34]
C:\Users\Marcel\Desktop\Projekte\C-Projekte\Bubblesort_Github\cmake-build-debug\Bubblesort_Github.exe
Enter the value number 1
2
2
would you enter an other value (1:Continue/0:Sort the actual array)?
1
1
Enter the value number 2
3
3
would you enter an other value (1:Continue/0:Sort the actual array)?
1
1
Enter the value number 3
4
4
would you enter an other value (1:Continue/0:Sort the actual array)?
1
1
Enter the value number 4
1
1
would you enter an other value (1:Continue/0:Sort the actual array)?
0
0
1, 2, 3, 1811939332,
Process finished with exit code 0

**Comment by shashikedissanayake** [comment]
I follow the steps you are given in debug mode, but i got the expected result. The algorithm is correct and it is work fine. I attach the my debug mode results within this
![image](https://user-images.githubusercontent.com/19923512/30678320-dd048ce8-9e80-11e7-900b-cc430b7d89ee.jpg)

**Comment by sachinarora707** [comment]
@MNCODE It's working fine for me as well.
