### ISSUE TITLE
Add more algorithms

### ISSUE THREAD

**Issue by AnupKumarPanwar** [TheAlgorithms/C#37]
Please add more algorithms to this repo. 

See the structure and README of this repo for reference
https://github.com/TheAlgorithms/Python

**Comment by prakamya-mishra** [comment]
I would like to contribute merge sort algorithm for hactoberfest. when should i give a pull request for   it after 1st october ?

**Comment by prakamya-mishra** [comment]
Sorry I meant code for All types of Linked List not merge sort.

**Comment by AnupKumarPanwar** [comment]
Yeah sure, go ahead and send pull request

**Comment by prakamya-mishra** [comment]
Please look over #38

**Comment by prakamya-mishra** [comment]
rest all i will send after october 1st

**Comment by AnupKumarPanwar** [comment]
Merged

**Comment by prakamya-mishra** [comment]
Thank you

**Comment by prakamya-mishra** [comment]
I have a Question:
All my pull request should reference to this issue then only will it get counted in hacktoberfest?

**Comment by kartikey-singh** [comment]
Please review the new fat.c added by me (Dynamic Programming Version)

**Comment by jebinphilipose** [comment]
Please review my PR's (#51 and #52)

**Comment by vagita24** [comment]
hi @AnupKumarPanwar 
I am a begineer. I want to contribute in Algos. Can you tell me the name of algos to contribute and language to use.

**Comment by prakamya-mishra** [comment]
Please review my PR's #53

**Comment by MadhavBahlMD** [comment]
Hey.
Operating systems related algorithms are missing.
If you want, i can add some?

**Comment by hegdenaveen1** [comment]
Is the Project Euler Branch in this repo serious?

**Comment by christianbender** [comment]
@hegdenaveen1  of course

**Comment by Rupeshiya** [comment]
hi
i have added sorting of linked list using selection sort and also stack implementation by using array 
look after #115

**Comment by maysanchez** [comment]
Hi @AnupKumarPanwar  
Could you review my PR #138, please ?

**Comment by JRaiden16** [comment]
> 
> 
> Please add more algorithms to this repo.
> 
> See the structure and README of this repo for reference
> https://github.com/TheAlgorithms/Python

Did you want some algorithms in particular? I have one that searches the GCD of two numbers by using Euclid's Algorithm, and another one that uses that GCD to code a message using RSA Algorithm

**Comment by deadPix3l** [comment]
are you only looking for serious algorithms that you would want to run? there are several algorithms that are mostly for joke, but are technically regarded as real algorithms.

**Comment by Time12345** [comment]
I think algorithms are difficult for me, I don't know how to study it.

**Comment by yoyou446** [comment]
DFS and BFS?

**Comment by nikhithabhupal2000** [comment]
Hi everyone!
I wrote the fractional knapsack and optimal merge patterns using greedy paradigm . Can I start a pull request? This is my first start to open source contribution so any suggestions would help 

Thanks in advance!

**Comment by siddarthspai** [comment]
I would like to add scan and cscan disk scheduling algorithms

**Comment by ZykielErx** [comment]
Hi @AnupKumarPanwar 
Please look at #343 #344 #345 #346 sorting algo

**Comment by kvedala** [comment]
Closing this issue as it seems outdated.
