### ISSUE TITLE
Implimentation for the Trie data structure 

### ISSUE THREAD

**Issue by shashikedissanayake** [TheAlgorithms/C#39]
In the data structure section there doesn't have Trie data structure. A Trie is a special data structure used to store strings that can be visualized like a graph.That is mostly used in Search Engines, Genome Analysis, Data Analytics. So I would like to implement Trie using C.

**Comment by dynamitechetan** [comment]
Sure. 🎉

**Comment by shashikedissanayake** [comment]
For the testing purpose should I have to write a main method to demonstrate the implementation?
