### ISSUE TITLE
Translation of README.md

### ISSUE THREAD

**Issue by JRaiden16** [TheAlgorithms/C#392]
You think is a good idea to add translations of the README.md?
I can write the spanish version.

**Comment by viveky1794** [comment]
This will help many students in India. Those who are not good into English.
I think I can write 

> Hindi version.

**Comment by ismaelcostarc** [comment]
I can translate the REAME.md to brazilian portuguese.

**Comment by kurnaz43** [comment]
I can do it for Turkish

**Comment by omonimus1** [comment]
I can translate in Italian

**Comment by devraj4522** [comment]
If anyone help I can translate in Hindi

**Comment by kvedala** [comment]
👍  Sure. We also have an online documentation website the https://thealgorithms.github.io/C on which this can render well.
The other option is to simple add a header for google translate. Then, the whole website can be translated for any of the supported languages. It does have the drawback that the translations are not always guaranteed to be correct.

**Comment by vicpb** [comment]
> I can translate the REAME.md to brazilian portuguese.

I can help you!
