### ISSUE TITLE
Heapsort program doesn't seem to work when you pass in an already sorted list

### ISSUE THREAD

**Issue by ericcurtin** [TheAlgorithms/C#502]
Enter the size of the array you want
5
Enter numbers separated by a comma:
1,2,3,4,5 
[1, 2, 5, 3, 4]

**Comment by ericcurtin** [comment]
This fixes the issue:

https://github.com/TheAlgorithms/C/pull/507/files

**Comment by danghai** [comment]
You can specify the issue number in commit message. It automatically is closed when it is merged.
The reference link: https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
