### ISSUE TITLE
the array index could be -1

### ISSUE THREAD

**Issue by VincentGogo** [TheAlgorithms/C#509]
https://github.com/TheAlgorithms/C/blob/807abcd0e8b644f909452f53b422c8288d8a2554/sorting/gnome_sort.c#L9

**Comment by StepfenShawn** [comment]
Hi @VincentGogo ! 
This is gnome_sort's pseudo code：
```
procedure gnomeSort(a[]):
    pos := 0
    while pos < length(a):
        if (pos == 0 or a[pos] >= a[pos-1]):
            pos := pos + 1
        else:
            swap a[pos] and a[pos-1]
            pos := pos - 1
```  
But you said that the array index can be - 1, I don't quite understand why to do this,Could you provide the running result after modifying the code?
Thank you!

**Comment by VincentGogo** [comment]
@StepfenShawn The pseudo code is right, The C code at line 9 should be
`if ( pos == 0 || numbers[pos] >= numbers[pos-1]`

**Comment by StepfenShawn** [comment]
OK, I see. I'll fix it soon. Thank you!
