### ISSUE TITLE
Jogo de adivinha qual número é maior

### ISSUE THREAD

**Issue by frankstylle** [TheAlgorithms/C#540]
#include <stdio.h>
main (){
    int num, num2, menor,maior;
    printf("\n----------------------------------");
    printf("\n| JOGO DO NÚMERO MAIOR OU MENOR  |");
    printf("\n----------------------------------");
    printf("\n\nDigite o número 1: ");
    scanf("%d",&num);
    printf("\nDigite o número 2: ");
    scanf("%d", &num2);
        if (num > num2) 
        printf("\n\nNumero 1 é Maior que o Número 2");
       
        if (num < num2)
        printf("\n\nNumero 2 é Maior que o Número 1");
        
        else 
        printf("\n\nOs dois Números são iguais");
        
        
        
        
        
    
   

return (0);
}

**Comment by EkanshMangal** [comment]
Olá, posso resolver esse problema?

**Comment by frankstylle** [comment]
Ok
