### ISSUE TITLE
[BUG] multikey_quick_sort.c - erroneous

### ISSUE THREAD

**Issue by kvedala** [TheAlgorithms/C#576]
erroneous code sequences

## Description

* line# 259 -> while loop has invalid termination condition because pp variable is not initialized and garbage value.

## Steps to Reproduce

1.
2.
3.
4.

**Comment by Panquesito7** [comment]
Wasn't this fixed in #601?

**Comment by kvedala** [comment]
Yes. Forgot to link the PR. Thanks for reminder.
