### ISSUE TITLE
2 Search folders

### ISSUE THREAD

**Issue by AnupKumarPanwar** [TheAlgorithms/C#60]
There are 2 separate folders in the repo for searching algorithms. Merge them.

**Comment by Yogendra0Sharma** [comment]
@AnupKumarPanwar : the Searches folder has only one file for BinarySearch algorithm and searching folder already have this file with same content. 
do we directly remove the Search folder and keep searching folder as it is ? because of no need to merge both the folder.

**Comment by AnupKumarPanwar** [comment]
Merged 2 sorts for sorting algorithms
