### ISSUE TITLE
[BUG]: No contributing guidelines in the repository

### ISSUE THREAD

**Issue by kudoabhijeet** [TheAlgorithms/C#609]
## Description
CONTRIBUTIONS.MD  redirects to a not found page.

## Expected Behavior

Should redirect to a markdown file. CONTRIBUTIONS.MD
## Actual Behavior

CONTRIBUTIONS.MD not exists, redirects to 404 not found.
## Possible Fix

Adding/creating a CONTRIBUTIONS.MD file.
## Steps to Reproduce

1. https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md -  404 page

## Context

Can't access contributing guidelines to contribute to the project.

**Comment by Panquesito7** [comment]
There is no `CONTRIBUTING.md` in this repository.
I think we shall look into adding it in the repository.

@kvedala what's your opinion about this? 🙂

**Comment by harshcut** [comment]
Issuing separate PRs for different types of commits might help, as there may be some changes that some like but not others.
