### ISSUE TITLE
Hacktoberfest 2020 - Implement C algorithms or data structures, fix existing ones and more! 

### ISSUE THREAD

**Issue by dynamitechetan** [TheAlgorithms/C#633]
The annual [Hacktoberfest](https://hacktoberfest.digitalocean.com/) is around the corner! Register on [Hacktoberfest's website](https://hacktoberfest.digitalocean.com/) and open 4 pull requests during October 2020 to receive the swags (if you're the first 70,000 participants)!

In our C repository, there are currently several open issues:

What's more, you can also **fix an existing bugs, improve any documentation** and **provide better implementations** for [certain algorithms](https://github.com/TheAlgorithms/C/blob/master/DIRECTORY.md)! Feel free to inform the community by **filling an issue** and start hacking! If you're new to contributing code, please read our [Contribution Guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md) for an overall understanding and ask questions on the internet - Google, StackOverflow or our Gitter.

[TheAlgorithms](https://github.com/TheAlgorithms) has repositories in other programming languages, so find your language and start coding there!

### What you can do to participate
1. Read our [Contribution Guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md)
2. Comment below or open an issue (for big ideas you may want the community to know) on your new implementations, fixes or functionalities
3. Start hacking!
4. Open a pull request for your contribution
5. Label your pull requests with `hacktoberfest`
6. Wait until your pull requests get reviewed or merged! In the meantime, you can review someone else's pull requests too

### Useful links
* Our [Gitter](https://gitter.im/TheAlgorithms) channel
* The [Contribution Guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md) of TheAlgorithms/C
* Our [Code of Conduct](https://github.com/TheAlgorithms/.github/blob/master/CODE_OF_CONDUCT.md)
* The [Directory](https://github.com/TheAlgorithms/C/blob/master/DIRECTORY.md) of TheAlgorithms/C

### Remarks
* Please observe Hacktoberfest's rules, terms and FAQ. If a pull request is marked `invalid` or `spam` it would not be counted and the person may be disqualified for the swags.
* Hacktoberfest 2020 is an event presented by DigitalOcean, Intel and DEV.

**Comment by Panquesito7** [comment]
@ayaankhan98 was it intentional to close this issue?

**Comment by ayaankhan98** [comment]
Not closed this manually, this is triggered by last merge. Moreover hacktoberfest is over so it's fine to close this now.
