### ISSUE TITLE
Logical Error Fixed

### ISSUE THREAD

**Issue by Suraj-Patro** [TheAlgorithms/C#713]
## Description

Bug fixed in conversions/c_atoi_str_to_integer.c & formatting
Logical error fixed in conversions/c_atoi_str_to_integer.c

## Expected Behavior

Should succesfully pass all assertions

## Actual Behavior

Fails to pass all assertions.

## Possible Fix

```
     if (str[i] == '-')
+    {
         sign = -1;
+        i++;
+    }
     else if (str[i] == '+')
+    {
         sign = 1;
+        i++;
+    }
```

## Steps to Reproduce

Compile & Execute Code.

## Context

Failed to assert all the checks.

@Suraj-Patro
https://github.com/Suraj-Patro/C/blob/master/conversions/c_atoi_str_to_integer.c

**Comment by Panquesito7** [comment]
Please create a PR and we'll review it. Thank you. 🙂
