### ISSUE TITLE
[FEATURE] Adding Cycle detection in linked list code

### ISSUE THREAD

**Issue by garimamangal19** [TheAlgorithms/C#714]

**Comment by Panquesito7** [comment]
Please describe as much as possible about this algorithm. Thank you.

**Comment by bhavdeep009** [comment]
are you looking for the code which detects cycle in link list?

**Comment by Panquesito7** [comment]
You haven't filled the template: it doesn't have description (not even detailed), context or possible implementation.
Please fill the template how does this algorithm work (or at least a description), context and possible implementation.

Thank you.

**Comment by ankitakul** [comment]
Hello, is this issue still open?  I have a project for a software methodology class to contribute to an open source repo and I would like to work on this project. Could I be assigned to this issue? 

Possible implementation: I was thinking of using 2 pointers, slow and fast. Slow pointer will move one step forward and fast pointer will move 2 steps forward. If they are pointing to same node, we know its a loop. If the fast reaches the null/end, it has no loop.

**Comment by Panquesito7** [comment]
Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* The algorithm isn't a duplicate in this repository.
* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

**Comment by ankitakul** [comment]
Hello, My code is ready. I made sure its not duplicate and according to standards.  I am new to github and  I am having issues pushing the code. It is saying invalid username and password , authentication failed for github/TheAlgorithms/C.git.  
Is it because I am not assigned the issues?  Can you please assign it to me.

**Comment by ayaankhan98** [comment]
> Hello, My code is ready. I made sure its not duplicate and according to standards. I am new to github and I am having issues pushing the code. It is saying invalid username and password , authentication failed for github/TheAlgorithms/C.git.
> Is it because I am not assigned the issues? Can you please assign it to me.

No it has no relation with issue assignment. It is because of your improper login configuration for Github CLI.

**Comment by ankitakul** [comment]
![Capture](https://user-images.githubusercontent.com/47610108/111711941-1b688680-8823-11eb-9613-d663c0feafeb.PNG)


I am getting this error now.

**Comment by Panquesito7** [comment]
> I am getting this error now.

You must [fork](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/cloning-and-forking-repositories-from-github-desktop#forking-a-repository) the repository, then clone your forked repository. 🙂

**Comment by ankitakul** [comment]
I was able to create a pull request after forking the repository. Thank you very much for your support!!  😊

**Comment by Arjun-Dagar** [comment]
Can i work on it?

**Comment by Panquesito7** [comment]
> Can I work on it?

Sure, if you want. I'll review your PR as soon as possible. 🙂
Just follow the steps mentioned in this issue above [**here**](https://github.com/TheAlgorithms/C/issues/714#issuecomment-778542952).
