### ISSUE TITLE
[BUG] Unhandled Exception in Tic-tack-toe-game

### ISSUE THREAD

**Issue by devraj4522** [TheAlgorithms/C#729]
Tick-Tack-Toe game is not working for exception part
## Description

Else part on line 247 takes you to infinite loop on getting any char value as input for position.

## Expected Behavior

It should give the option to enter value again

## Actual Behavior

Infite Loop with print value - Invalid value

**Comment by 123mansha** [comment]
hii want to work on this issue please tell me the error and assign it to me

**Comment by hero4127** [comment]
Hi want to work with this issue please assign it to as I have much experience in C program and I have excellent logic developed.

**Comment by Panquesito7** [comment]
Please don't ask to be assigned. See the [contributing guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#contributor).
If you want to help with this, submit a PR and maintainers will review it.

Thank you. 🙂

**Comment by kana800** [comment]
@Panquesito7  I fixed the bugs 😄

**Comment by north8side** [comment]
Good work

**Comment by north8side** [comment]
C++ is not the best for it's function needs more
