### ISSUE TITLE
[BUG] Added limits.h in data_structures/heap/max_heap.c

### ISSUE THREAD

**Issue by Suraj-Patro** [TheAlgorithms/C#758]
## Description

bug fixed added limits.h at data_structures/heap/max_heap.c

## Expected Behavior

code should compileand execute

## Actual Behavior

Code throws error on execution

## Possible Fix

include limits.h

## Steps to Reproduce

compile and execute the code

**Comment by mainak-debnath** [comment]
I would like to take care of this issue.

**Comment by Panquesito7** [comment]
> I would like to take care of this issue.

Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.
