### ISSUE TITLE
[BUG] Fixed error relating importing of Header file at data_structures/array/carray.c

### ISSUE THREAD

**Issue by Suraj-Patro** [TheAlgorithms/C#762]
## Description

Fixed error relating importing of Header file at data_structures/array/carray.c

## Expected Behavior

code should compile and execute

## Actual Behavior

code throughs error on compilation

## Possible Fix

include the custom header file with proper name

## Steps to Reproduce

compile and execute

**Comment by RavishankarreddyB** [comment]
Hi @Suraj-Patro , I'm interested in fixing this. 
I've few questions - 

- I'm getting a warning (**not error**) when trying to compile the carray.c file regarding the name of the header file. Are you referring to that or some other thing ?

``` 
gcc carray.c -c
carray.c:29:10: warning: non-portable path to file '"carray.h"'; specified path differs in case from file name on disk [-Wnonportable-include-path]
#include "CArray.h"
         ^~~~~~~~~~
         "carray.h"
1 warning generated.
```

- Same question for the carray_tests.c file as well.

**Comment by Suraj-Patro** [comment]
Same here.
It does generate a warning.
On execution, it results into a runtime error. because of the mis-spelled file name.

**Comment by RavishankarreddyB** [comment]
@Suraj-Patro , So is the fix just changing to proper file name or anything else ?

**Comment by Suraj-Patro** [comment]
Its about changing code of the header file included at the "#include preprocessor directive" in the data_structures/array/carray.c
pertaining to the mis-spelled file name "CArray.h" to "carray.h".
