### ISSUE TITLE
[BUG] Added stdlib.h

### ISSUE THREAD

**Issue by Suraj-Patro** [TheAlgorithms/C#767]
## Description

Added stdlib.h at data_structures/linked_list/singly_link_list_deletion.c

## Expected Behavior

code should compile

## Actual Behavior

functons definition not known exception

## Steps to Reproduce

include stdlib.h

**Comment by jaguar-kannan** [comment]
iam intrested can i do this

**Comment by Panquesito7** [comment]
> can I do this

Thank you for your interest in contributing. 👍
Before submitting a PR, please ensure the following:

* Make your code as per the repository [standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).
* Ensure that the all the [automated-tests](https://github.com/TheAlgorithms/C-Plus-Plus/actions) pass.

**Comment by SInisterChil** [comment]
Can I do this?

**Comment by Panquesito7** [comment]
Sure; please read my message above. Thank you.
