### ISSUE TITLE
Make code more modular in nature

### ISSUE THREAD

**Issue by shivam-tripathi** [TheAlgorithms/C#78]
Presently, each algorithm implementation requires implementation of each underlying data structure from scratch. This is a hassle, as more than often the implementations of underlying data structures increases the code size unnecessarily. 
For example, while implementing graph algorithms if we have to reimplement graph ADT again it will meaningless. Instead it would be good idea to implement a header file alongside, which could be used as includes later in other algorithms. 
This issue aims to provide such modular nature in the present existing files.

**Comment by kenshimota** [comment]
valla no sabia eso gracias por el dato brou

**Comment by kenshimota** [comment]
:) :) :D
