### ISSUE TITLE
Wanted to add infix to postfix conversion program using stack in c 

### ISSUE THREAD

**Issue by UG-SEP** [TheAlgorithms/C#825]
Hey,
I saw there is no program related to infix to postfix conversion program can i add 
Example 
Input: a+b * c
Output: abc * +
Please assign me 
Thanks

**Comment by Panquesito7** [comment]
There's already an [Infix to Postfix](https://github.com/TheAlgorithms/C/blob/master/conversions/infix_to_postfix.c) algorithm here. You can create a Postfix to Infix algorithm, though. 🙂
