### ISSUE TITLE
Wanted to add Paint App in C language

### ISSUE THREAD

**Issue by UG-SEP** [TheAlgorithms/C#826]
Hey,
I have cool project Paint With UG a Desktop application so can i add my project.
[Project Link](https://github.com/UG-SEP/Paint-with-UG-The-SEP)
```javascript
if(You Like Project)
{
So please give a star⭐
also assign me to add the project
and tell me that whether i have to add my project in games folder or  create a new folder 
if(New)
{
Tell me a suitable folder name
}
} 
```
Thanks

**Comment by Panquesito7** [comment]
I'm not so sure if this is suitable for this repository. By the way,
you should make an issue in the [C++](https://github.com/TheAlgorithms/C-Plus-Plus), as your app is written in C++.

@ayaankhan98 @cclauss, thoughts?

**Comment by ayaankhan98** [comment]
> I'm not so sure if this is suitable for this repository. By the way,
> you should make an issue in the [C++](https://github.com/TheAlgorithms/C-Plus-Plus), as your app is written in C++.
> 
> @ayaankhan98 @cclauss, thoughts?

I will not prefer to integrate projects within algorithms repository.
By the way we can create separate repository within the organisation for beginners project (educational purpose), then these things can be added in that repository.

**Comment by UG-SEP** [comment]
> I'm not so sure if this is suitable for this repository. By the way,
> you should make an issue in the [C++](https://github.com/TheAlgorithms/C-Plus-Plus), as your app is written in C++.
> 
> @ayaankhan98 @cclauss, thoughts?

yes you are right

**Comment by Panquesito7** [comment]
@AnupKumarPanwar?

**Comment by UG-SEP** [comment]
> > I'm not so sure if this is suitable for this repository. By the way,
> > you should make an issue in the [C++](https://github.com/TheAlgorithms/C-Plus-Plus), as your app is written in C++.
> > @ayaankhan98 @cclauss, thoughts?
> 
> I will not prefer to integrate projects within algorithms repository.
> By the way we can create separate repository within the organisation for beginners project (educational purpose), then these things can be added in that repository.

Please invite to the community

**Comment by cclauss** [comment]
Unfortunately, it is not an algorithm.
