### ISSUE TITLE
[FEATURE] Add `reverse()` function to doubly_linked_list.c

### ISSUE THREAD

**Issue by ybrenning** [TheAlgorithms/C#934]
### Detailed description

Add a simple function `reverse()` to reverse a given doubly linked list.

### Context

It is a very common algorithm for linked lists and is quite easy to implement for doubly linked lists especially.

**Comment by rgarrettrun** [comment]
Hello, I would like to work on this issue.

**Comment by ybrenning** [comment]
Hey, I have already resolved this issue in PR #935 , it is just waiting on approval
