### ISSUE TITLE
[BUG] Cannot compile with ARM-Cortex processors

### ISSUE THREAD

**Issue by chent11** [TheAlgorithms/C#943]
### Description

When an ARM GCC compiles the code below,

```
geometry/vectors_3d.c:10 #include <arm_math.h>
geometry/quaternions.c:10 #include <arm_math.h>
```

it will complain about the lacking of "arm_math.h" file. Because this is not a standard C math library, you need to add the CMSIS-DSP library to your project and tell the compiler to link it so that it can be compiled.

### Expected behavior

No errors would prompt

### Actual behavior

fatal error: arm_math.h: No such file or directory

### Possible fix

Add CMSIS-DSP library to this repo

### Steps to reproduce

Use an ARM GCC to compile this repo

### Context

-

**Comment by mucahitdemir** [comment]
If you use ST CubeMx IDE, in the Project section, select _include all the necessary library files_ option

**Comment by Panquesito7** [comment]
CC: @TheAlgorithms/c_maintainer
