### ISSUE TITLE
Add "maximum consecutive ones"

### ISSUE THREAD

**Issue by zugzwang03** [TheAlgorithms/C#974]
### Detailed description

I want to add the solution of "maximum consecutive ones" in the leetcode directory.
I want to make this contribution under hacktoberfest'22.
Question link : https://leetcode.com/problems/max-consecutive-ones/

### Context

The number of questions covered in leetcode directory is low. So the addition of one more would benefit any way.
Otherwise also, Maximum consecutive ones is an easy but common question for interviews.

**Comment by devarshitrivedi01** [comment]
can I work on this?

**Comment by Appy-007** [comment]
@zugzwang03 can I work on the issue?

**Comment by JKP0495** [comment]
please assign this to me, i will do it in a day...

**Comment by Prathamrajbhatt** [comment]
Hey! Can you assign this issue to me?

**Comment by ankpal145** [comment]
Can you please assign this issue to me? I can submit it in 4 hour.

**Comment by zugzwang03** [comment]
With great sorrow, I need to say that the project admin of this project is inactive as can be seen. I created that issue to be self-assigned, but since it has been left just like that for 7 long days, so I am closing it. Probably this repo is not participating in hacktoberfest this year.
