### ISSUE TITLE
In C/data_structures/linked_list/ The algorithms present are missing Imp pattern topics of Linked List.

### ISSUE THREAD

**Issue by deoliaman00** [TheAlgorithms/C#987]
### Detailed description

While working with Linked List DS , the beginner needs to learn topic Like:-
1. How to reverse a linked list
2. Check a loop inside a linked list
3. Check the given linked list is pallindrome or not.

### Context

These topics help the beginner to get hands on with strong foundation.

**Comment by deoliaman00** [comment]
Kindly assign me this issue and I am willing to help asap.

**Comment by Shubhamsingh2747** [comment]
Hey, kindly assign me this issue. I can provide C++ code.

**Comment by JKP0495** [comment]
please assign this to me, i can provide c code in very short time

**Comment by anjisnu07** [comment]
Hey buddy, assign me for this..

**Comment by SrijaMarripelli** [comment]
@deoliaman00 please assign this to me

**Comment by SohamPashteSSP** [comment]
Hello, please assign me this, I can provide solution for in C language for reversing a linked list
